# Generated by Django 5.2.5 on 2025-11-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentMovement',
            fields=[
                ('inventorymovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventorymovement')),
                ('motive', models.CharField(max_length=200)),
            ],
            bases=('inventory.inventorymovement',),
        ),
        migrations.CreateModel(
            name='EntryMovement',
            fields=[
                ('inventorymovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventorymovement')),
            ],
            bases=('inventory.inventorymovement',),
        ),
        migrations.CreateModel(
            name='ExitMovement',
            fields=[
                ('inventorymovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventorymovement')),
                ('destination', models.CharField(max_length=200)),
            ],
            bases=('inventory.inventorymovement',),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='gemstone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.gemstone'),
        ),
    ]
