# Generated by Django 5.2.5 on 2025-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('adjustment', 'Ajuste')], default='entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='adjustmentmovement',
            name='motive',
            field=models.CharField(choices=[('damage', 'Daño'), ('loss', 'Pérdida'), ('regulation', 'Regulación IMMEX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exitmovement',
            name='destination',
            field=models.CharField(choices=[('prod', 'Producción'), ('sales', 'Ventas')], max_length=20),
        ),
    ]
